# Generated by Django 3.0.5 on 2020-04-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_auto_20200428_1836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_pass',
        ),
        migrations.AlterField(
            model_name='post',
            name='user_email',
            field=models.CharField(max_length=50),
        ),
    ]
